**PyTorch tensor**

A tensor is a data structure or data container we use in PyTorch for carrying arrays of numbers.

**a. Creating a tensor**

In [ ]:
pip install torch

In [ ]:
import torch
import numpy as np

In [ ]:
# Construct a tensor from an array
array = [[1, 2], [7, 4], [5, 6]]
tensor0 = torch.tensor(array)
print(tensor0)
print("The data structure type of tensor0: ", type(tensor0))
print("The data type of tensor0: ", tensor0.dtype)
print("The shape of tensor0: ", tensor0.shape)

tensor([[1, 2],
        [7, 4],
        [5, 6]])
The data structure type of tensor0:  <class 'torch.Tensor'>
The data type of tensor0:  torch.int64
The shape of tensor0:  torch.Size([3, 2])


In [ ]:
# Construct a tensor from a numpy array
np_array = np.array([[1, 2], [7, 4], [5, 6]])
tensor1 = torch.tensor(np_array)
print(tensor1)

tensor([[1, 2],
        [7, 4],
        [5, 6]])


**b. Common Methods: Slicing and Concatenation**

*Slicing*

In [ ]:
tensorA = torch.tensor([[1, 1, 1], [2, 2, 2]])
tensorB = torch.tensor([[3, 3, 3], [4, 4, 4]])

In [ ]:
# Slicing is all the same as numpy arrays
print('Slicing the first two rows of tensorA (index one inclusive index two exclusive): ')
print(tensorA[:2])
print('Slicing the first two columns of tensorA (take all rows, then slice columns): ')
print(tensorA[:, :2])

Slicing the first two rows of tensorA (index one inclusive index two exclusive): 
tensor([[1, 1, 1],
        [2, 2, 2]])
Slicing the first two columns of tensorA (take all rows, then slice columns): 
tensor([[1, 1],
        [2, 2]])


*Concatenation*

In [ ]:
print('Vertically concatenate tensorA and tensorB: (default: dim=0)')
concat_v = torch.cat([tensorA, tensorB]) # wrap them in an array
print(concat_v)

Vertically concatenate tensorA and tensorB: (default: dim=0)
tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4]])


In [ ]:
print('Horizontally concatenate tensorA and tensorB: (dim=1)')
concat_h = torch.cat([tensorA, tensorB], dim=1)
print(concat_h)

Horizontally concatenate tensorA and tensorB: (dim=1)
tensor([[1, 1, 1, 3, 3, 3],
        [2, 2, 2, 4, 4, 4]])
